version: "3"
services:

  mongo:
    image: 'mongo'
    expose:
      - '27017'
    volumes:
      - mongo_data:/data/db
    env_file:
      - ./.env.mongodb

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    expose:
      - 3000
    depends_on:
      - mongo

volumes:
  mongo_data: