version: "3"
services:

  mongo:
    image: 'mongo'
    expose:
      - '27017'
    volumes:
      - mongo_data:/data/db
    env_file:
      - ./.env.mongodb

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    expose:
      - 3000
    depends_on:
      - mongo

  nginx:
     image: nginx:1.21.6-alpine
     restart: unless-stopped
     volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
       - ./nginx/api.conf.template:/etc/nginx/templates/api.conf.template:ro
       - ./certificates/letsencrypt:/etc/letsencrypt
       - ./certificates/certbot:/var/www/certbot
     ports:
       - "80:80"
       - "443:443"
     env_file:
       - ./.env
     depends_on:
       - api

volumes:
  mongo_data: